version: 0.2
  - name: "AWS CodeBuild run build" Action For GitHub Actions
    uses: aws-actions/aws-codebuild-run-build@v1.0.1

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/uberanalytics-1.0.jar
